version: '2'
services:
  opencart:
    build: .
    environment:
      XDEBUG_CONFIG: remote_host=HOST IP (the machine that sets the breakpoints)
    links:
      - db
    ports:
      - "3000:80"
  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: opencart
